### ISSUE TITLE
decide on individual website ideas

### ISSUE THREAD

**Issue by Apollo-XIV** [UA92-DevOps-Apprentices-Org/Group-Project-2#3]
- [x] Luis
- [x] Alex
- [x] Graham
- [x] Amaan
- [x] Kenan
- [x] Nick

**Comment by LuisRuivo21** [comment]
I will keep my initial website idea, which is a news/blog that displays articles related to technology and astronomy. The website aims to keep users up-to-date regarding new technologies and the newest space discoveries.

**Comment by icybox129** [comment]
I will create either a blog (probably gaming related) or some web app (that focuses on exercise/gym etc), incorporating javascript.

**Comment by Manchester23** [comment]
MERN stack application (React, Express, Mongo DB, Node), demonstrating CRUD functionality. Property booking website, similar to booking.com. Retail element: customer who are looking for short stay holiday homes.

**Comment by Vanilla-G** [comment]
something simple, possibly fun and easy to build, either a parody site documenting the release of new AI company called "Skynet" (terminator franchise) or keep my project 1 website as is and just finish it off.
